# PowerShell equivalent of audit-source.sh -- for Windows users.
#
# Usage (from project root):
#   pwsh webflow-to-shopify-kit/scripts/audit-source.ps1

param([string]$SourceDir = "webflow-source")

$ErrorActionPreference = "Stop"
$Out = "AUDIT.md"

if (-not (Test-Path $SourceDir -PathType Container)) {
    Write-Error "$SourceDir/ not found. Drop your Webflow export there first."
    exit 1
}

$lines = @()
$lines += "# Webflow export audit"
$lines += ""
$lines += "_Generated by ``webflow-to-shopify-kit/scripts/audit-source.ps1`` against ``$SourceDir/``._"
$lines += ""

# data-wf-site
$lines += "## data-wf-site (constant -- paste into theme.liquid + password.liquid)"
$lines += ""
$lines += '```'
$siteMatches = Select-String -Path "$SourceDir/*.html" -Pattern 'data-wf-site="[^"]+"' -AllMatches |
    ForEach-Object { $_.Matches } | ForEach-Object { $_.Value } | Sort-Object -Unique
$lines += $siteMatches
$lines += '```'
$lines += ""

# data-wf-page per page
$lines += "## data-wf-page (one per HTML page -- paste into the case-switch in theme.liquid)"
$lines += ""
$lines += "| File | data-wf-page |"
$lines += "|---|---|"
foreach ($f in Get-ChildItem "$SourceDir/*.html") {
    $m = Select-String -Path $f.FullName -Pattern 'data-wf-page="([^"]+)"' | Select-Object -First 1
    $pageId = if ($m) { $m.Matches[0].Groups[1].Value } else { "(none)" }
    $lines += "| $($f.Name) | ``$pageId`` |"
}
$lines += ""

# Reusable components
$lines += "## Reusable component sections (will become sections/component-*.liquid)"
$lines += ""
$lines += "Per-page list of ``component_*_section`` classes -- components appearing in 2+ pages are good candidates for the ``split-page.cjs`` reusable-section pattern."
$lines += ""
foreach ($f in Get-ChildItem "$SourceDir/*.html") {
    $lines += "### $($f.Name)"
    $lines += ""
    $lines += '```'
    $comps = Select-String -Path $f.FullName -Pattern '<section[^>]*class="[^"]*component_[a-z_]+_section[^"]*"' -AllMatches |
        ForEach-Object { $_.Matches } | ForEach-Object { $_.Value } |
        ForEach-Object { if ($_ -match 'component_[a-z_]+_section') { $matches[0] } } | Sort-Object -Unique
    $lines += $comps
    $lines += '```'
    $lines += ""
}

# Webflow JS bundle
$lines += "## Webflow JS bundle (asset filename -- paste into theme.liquid)"
$lines += ""
$lines += '```'
$js = Select-String -Path "$SourceDir/*.html" -Pattern 'src="js/([^"]+\.js)"' -AllMatches |
    ForEach-Object { $_.Matches } | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique
$lines += $js
$lines += '```'
$lines += ""

# CSS files
$lines += "## CSS files (asset filenames)"
$lines += ""
$lines += '```'
if (Test-Path "$SourceDir/css") {
    $lines += (Get-ChildItem "$SourceDir/css" -File | ForEach-Object { $_.Name })
} else {
    $lines += "(no css/ folder found)"
}
$lines += '```'
$lines += ""

# Asset folders
$lines += "## Asset folders (will flatten into assets/)"
$lines += ""
foreach ($d in @("css", "js", "images", "fonts")) {
    if (Test-Path "$SourceDir/$d") {
        $count = (Get-ChildItem "$SourceDir/$d" -File).Count
        $lines += "- ``$d/`` -- $count files"
    }
}
$lines += ""

# Forms
$lines += "## Forms (need manual conversion per CONVERSION_GUIDE §8)"
$lines += ""
$lines += '```'
$forms = Select-String -Path "$SourceDir/*.html" -Pattern 'id="wf-form-[A-Za-z0-9_-]+"' -AllMatches |
    ForEach-Object { $_.Matches } | ForEach-Object { $_.Value } | Sort-Object -Unique
$lines += $forms
$lines += '```'

$lines -join "`n" | Set-Content -Path $Out -Encoding utf8

Write-Host ""
Write-Host "OK Audit written to $Out" -ForegroundColor Green
Write-Host "  Open it, then use the data-wf-site + data-wf-page values in Step 7."
