#!/usr/bin/env bash
# Audits a Webflow export and writes the findings to AUDIT.md at the project
# root. You'll reference AUDIT.md in Step 7 when filling layout placeholders.
#
# Usage (from project root, after dropping the export into webflow-source/):
#   bash webflow-to-shopify-kit/scripts/audit-source.sh

set -e

SOURCE_DIR="${1:-webflow-source}"
OUT="AUDIT.md"

if [ ! -d "$SOURCE_DIR" ]; then
  echo "ERROR: $SOURCE_DIR/ not found. Drop your Webflow export there first." >&2
  exit 1
fi

cd "$(pwd)"

{
  echo "# Webflow export audit"
  echo ""
  echo "_Generated by \`webflow-to-shopify-kit/scripts/audit-source.sh\` against \`$SOURCE_DIR/\`._"
  echo ""

  echo "## data-wf-site (constant — paste into theme.liquid + password.liquid)"
  echo ""
  echo '```'
  grep -ohE 'data-wf-site="[^"]+"' "$SOURCE_DIR"/*.html | sort -u
  echo '```'
  echo ""

  echo "## data-wf-page (one per HTML page — paste into the case-switch in theme.liquid)"
  echo ""
  echo "| File | data-wf-page |"
  echo "|---|---|"
  for f in "$SOURCE_DIR"/*.html; do
    page_id=$(grep -o 'data-wf-page="[^"]*"' "$f" | head -1 | sed 's/data-wf-page="//;s/"//')
    echo "| $(basename "$f") | \`$page_id\` |"
  done
  echo ""

  echo "## Reusable component sections (will become sections/component-*.liquid)"
  echo ""
  echo "Per-page list of \`component_*_section\` classes — components appearing in 2+ pages are good candidates for the \`split-page.cjs\` reusable-section pattern."
  echo ""
  for f in "$SOURCE_DIR"/*.html; do
    echo "### $(basename "$f")"
    echo ""
    echo '```'
    grep -oE '<section[^>]*class="[^"]*component_[a-z_]+_section[^"]*"' "$f" \
      | grep -oE 'component_[a-z_]+_section' | sort -u
    echo '```'
    echo ""
  done

  echo "## Webflow JS bundle (asset filename — paste into theme.liquid)"
  echo ""
  echo '```'
  grep -ohE 'src="js/[^"]+\.js"' "$SOURCE_DIR"/*.html | sed 's|src="js/||;s|"||' | sort -u
  echo '```'
  echo ""

  echo "## CSS files (asset filenames — confirm these match what theme.liquid loads)"
  echo ""
  echo '```'
  ls -1 "$SOURCE_DIR"/css/ 2>/dev/null || echo "(no css/ folder found)"
  echo '```'
  echo ""

  echo "## Asset folders (will flatten into assets/)"
  echo ""
  for d in css js images fonts; do
    if [ -d "$SOURCE_DIR/$d" ]; then
      count=$(ls -1 "$SOURCE_DIR/$d" | wc -l)
      echo "- \`$d/\` — $count files"
    fi
  done
  echo ""

  echo "## Forms (need manual conversion per CONVERSION_GUIDE §8)"
  echo ""
  echo '```'
  grep -hoE 'id="wf-form-[A-Za-z0-9_-]+"' "$SOURCE_DIR"/*.html | sort -u
  echo '```'

} > "$OUT"

echo "✓ Audit written to $OUT"
echo "  Open it, then use the data-wf-site + data-wf-page values in Step 7."
